name: Pull feeds and publish

on:
  schedule:
    - cron: '0 0 * * 1' # weekly at 00:00 on Monday UTC -> https://crontab.guru/#0_0_*_*_1
  push:
    branches:
      - 'main'
    paths:
      - '**/*'
      - '!docs'
  workflow_dispatch:


jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./tools/rss_retriever # Sets the default CWD for all 'run' steps in this job
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ni/python-actions/setup-python@a2894c635a2cba635a1086c1f89796fec2c52f74 # v0.7.2
      - uses: ni/python-actions/setup-poetry@a2894c635a2cba635a1086c1f89796fec2c52f74 # v0.7.2
      - run: poetry install -v
      - name: cache feed data
        id: cache-feeds
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/cache-feeds
          key: ${{ runner.os }}-cache-feeds
      - name: Build feeds
        run: >
          poetry run python -m rss_retriever 
          --feed "https://www.youtube.com/feeds/videos.xml?channel_id=UCea_GJg5QGvycBOrYjjkMJg"
          --output-json --items-path feed/entry --item-id-key id
          --cache-dir ~/cache-feeds
          --out-dir ../../docs;
          
          poetry run python -m rss_retriever 
          --feed "https://anchor.fm/s/d5a0c50/podcast/rss"
          --output-json --items-path rss/channel/item --item-id-key link
          --cache-dir ~/cache-feeds
          --out-dir ../../docs
      - name: Store Cache dir as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: feeds-cache
          path: ~/cache-feeds/
      - name: Check for changes and commit/push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add "$GITHUB_WORKSPACE/docs"
          git diff --cached --exit-code --quiet || {
            git commit -m "Automated update (CI)"
            git push
          }
